# permissions for end users to edit namespaceddbcreds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceddbcreds-editor-role
rules:
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds/status
  verbs:
  - get
