# permissions for end users to view namespaceddbcreds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceddbcreds-viewer-role
rules:
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds/status
  verbs:
  - get
