
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds/finalizers
  verbs:
  - update
- apiGroups:
  - db.tarkalabs.com
  resources:
  - namespaceddbcreds/status
  verbs:
  - get
  - patch
  - update
